logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    continue-on-error: true
    driverClassName: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 600000
    password: postgres
    url: jdbc:postgresql://${database-host:db}:55432/ccf
    username: postgres
  flyway:
    clean-on-validation-error: true # TODO - remove once envs exist
    connectRetries: 600000
    locations: classpath:/db/migration
    password: postgres
    url: jdbc:postgresql://${database-host:db}:55432/ccf
    user: postgres
  security:
    enabled: true
    oauth2:
      client:
        registration:
          idam:
            provider: idam
            client-id: rse
            client-secret: bar
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - openid
              - roles
              - profile
        provider:
          idam:
            issuer-uri: ${IDAM_URI:http://localhost:8090/auth/realms/rse}

